algoritmo "Operadores relacionais"
//Apenas retorna se a operação é verdadeira ou não
var
   A,B,C: Real
inicio
      A <- 2
      B <- 3
      C <- 5
      Escreval (A>B)
      Escreval (A=B)
      Escreval (A<>B)
      Escreval (C=A+B)
      Escreval (B<=C%2)//o resto da divisão de C/2 é = B(3) ?
      Escreval (1=C%2)//o resto da divisão de C/2 é = 1 ?
      Escreva((A=B) ou (C>A))
fimalgoritmo